{
  "formatVersion": "1.1",
  "component": {
    "group": "me.totoku103",
    "module": "crypto",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0.2.jar",
          "url": "crypto-1.0.2.jar",
          "size": 101150,
          "sha512": "5110e974013a785372cadecc1ab59bcf335f52d97e97e4ea3f5035fa3298d3733bcb6a823ec4739beb26397e59c5c02083dc1143863e5e90caf84ef99464b05b",
          "sha256": "80644d7907ccbbaff8a7c66f85b85a23e7e6e8dbd7cf49e1c781e89253607d12",
          "sha1": "f3355dfcc8525ba286a0be2f0d071f456d7d4615",
          "md5": "92caddf2bf285c2e514a35c7e60def9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.5-jre"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.81"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0.2.jar",
          "url": "crypto-1.0.2.jar",
          "size": 101150,
          "sha512": "5110e974013a785372cadecc1ab59bcf335f52d97e97e4ea3f5035fa3298d3733bcb6a823ec4739beb26397e59c5c02083dc1143863e5e90caf84ef99464b05b",
          "sha256": "80644d7907ccbbaff8a7c66f85b85a23e7e6e8dbd7cf49e1c781e89253607d12",
          "sha1": "f3355dfcc8525ba286a0be2f0d071f456d7d4615",
          "md5": "92caddf2bf285c2e514a35c7e60def9b"
        }
      ]
    }
  ]
}
