{
  "formatVersion": "1.1",
  "component": {
    "group": "me.totoku103",
    "module": "crypto",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0.1.jar",
          "url": "crypto-1.0.1.jar",
          "size": 98831,
          "sha512": "7cd86033731768ab44f05a5331e3ec48ce0c73ed66e2b34a70f508b4682386f1c05ed93238947399c78b72e507a3576fbcb7ec41dc51368aeecb142cc2ae04b9",
          "sha256": "24541d2cc5277a9514614fb2ade8b1327e22536c848d047edaadfa765df04d8c",
          "sha1": "0aaf08f7dfbb92f3157d4be040b641e850eabc2e",
          "md5": "07594fac6a611a04b29b576c298853dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.81"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.5-jre"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "crypto-1.0.1.jar",
          "url": "crypto-1.0.1.jar",
          "size": 98831,
          "sha512": "7cd86033731768ab44f05a5331e3ec48ce0c73ed66e2b34a70f508b4682386f1c05ed93238947399c78b72e507a3576fbcb7ec41dc51368aeecb142cc2ae04b9",
          "sha256": "24541d2cc5277a9514614fb2ade8b1327e22536c848d047edaadfa765df04d8c",
          "sha1": "0aaf08f7dfbb92f3157d4be040b641e850eabc2e",
          "md5": "07594fac6a611a04b29b576c298853dd"
        }
      ]
    }
  ]
}
